// List of all languages supported by cld3
export const languageList = {
	"af": "Afrikaans",
	"am": "Amharic",
	"ar": "Arabic",
	"bg": "Bulgarian",
	"bg-Latn": "Bulgarian",
	"bn": "Bangla",
	"bs": "Bosnian",
	"ca": "Catalan",
	"ceb": "Cebuano",
	"co": "Corsican",
	"cs": "Czech",
	"cy": "Welsh",
	"da": "Danish",
	"de": "German",
	"el": "Greek",
	"el-Latn": "Greek",
	"en": "English",
	"eo": "Esperanto",
	"es": "Spanish",
	"et": "Estonian",
	"eu": "Basque",
	"fa": "Persian",
	"fi": "Finnish",
	"fil": "Filipino",
	"fr": "French",
	"fy": "Western Frisian",
	"ga": "Irish",
	"gd": "Scottish Gaelic",
	"gl": "Galician",
	"gu": "Gujarati",
	"ha": "Hausa",
	"haw": "Hawaiian",
	"hi": "Hindi",
	"hi-Latn": "Hindi",
	"hmn": "Hmong",
	"hr": "Croatian",
	"ht": "Haitian Creole",
	"hu": "Hungarian",
	"hy": "Armenian",
	"id": "Indonesian",
	"ig": "Igbo",
	"is": "Icelandic",
	"it": "Italian",
	"iw": "Hebrew",
	"ja": "Japanese",
	"ja-Latn": "Japanese",
	"jv": "Javanese",
	"ka": "Georgian",
	"kk": "Kazakh",
	"km": "Khmer",
	"kn": "Kannada",
	"ko": "Korean",
	"ku": "Kurdish",
	"ky": "Kyrgyz",
	"la": "Latin",
	"lb": "Luxembourgish",
	"lo": "Lao",
	"lt": "Lithuanian",
	"lv": "Latvian",
	"mg": "Malagasy",
	"mi": "Maori",
	"mk": "Macedonian",
	"ml": "Malayalam",
	"mn": "Mongolian",
	"mr": "Marathi",
	"ms": "Malay",
	"mt": "Maltese",
	"my": "Burmese",
	"ne": "Nepali",
	"nl": "Dutch",
	"no": "Norwegian",
	"ny": "Nyanja",
	"pa": "Punjabi",
	"pl": "Polish",
	"ps": "Pashto",
	"pt": "Portuguese",
	"ro": "Romanian",
	"ru": "Russian",
	"ru-Latn": "Russian",
	"sd": "Sindhi",
	"si": "Sinhala",
	"sk": "Slovak",
	"sl": "Slovenian",
	"sm": "Samoan",
	"sn": "Shona",
	"so": "Somali",
	"sq": "Albanian",
	"sr": "Serbian",
	"st": "Southern Sotho",
	"su": "Sundanese",
	"sv": "Swedish",
	"sw": "Swahili",
	"ta": "Tamil",
	"te": "Telugu",
	"tg": "Tajik",
	"th": "Thai",
	"tr": "Turkish",
	"uk": "Ukrainian",
	"ur": "Urdu",
	"uz": "Uzbek",
	"vi": "Vietnamese",
	"xh": "Xhosa",
	"yi": "Yiddish",
	"yo": "Yoruba",
	"zh": "Chinese Han",
	"zh-Latn": "Chinese",
	"zu": "Zulu"
}

export type languageCodes = keyof typeof languageList;

// Simplified list with no double entries
export const simplifiedList = Object.entries(languageList)
	.filter(([_, value]) => !(value.includes('Latn')))
	.reduce((accumulator: { [key: string]: string }, [key, value]) => {
		accumulator[key] = value;
		return accumulator;
	}, {} as { [key: string]: string });
