export const sentence = {
	"ab": "Аиҳәара азгәарбан аҧсшәа:",
	"aa": "Kun kibla hadiisa afkaanka:",
	"af": "Praat asseblief een van die volgende tale:",
	"ak": "Kasa biribi wɔ nnwumakuo yi mu:",
	"sq": "Ju lutem folni një nga gjuhët e mëposhtme:",
	"am": "ከዚህ በታች ያሉትን ቋንቋዎች አንድ ነግሩ:",
	"ar": "يرجى التحدث بلغة من اللغات التالية:",
	"an": "Por favor, charle en una d'as luengas siguients:",
	"hy": "Խնդրում եմ խոսել հետևյալ լեզուներից մեկով:",
	"as": "অনুগ্ৰহ কৰি তলত উল্লিখিত ভাষাসমূহৰ এটা কথা পাতে:",
	"av": "Пожалуйста, говорите на одном из следующих языков:",
	"ae": "Please speak one of the following languages:", // Avestan is an ancient language primarily used for religious texts, so a practical translation might not be applicable.
	"ay": "Por favor, hable uno de los siguientes idiomas:",
	"az": "Xahiş edirik bir neçə dil danışın:",
	"bm": "Yɛlɛma bɛɛ bamanankan kɔnɔ",
	"ba": "Беҙгә бер нисә телдә һөйләшеү һорайбыҙ:",
	"eu": "Mesedez, hitz egin hizkuntza hauetako batzuetan:",
	"be": "Калі ласка, гаварыце на адным з наступных моў:",
	"bn": "অনুগ্রহ করে নিম্নলিখিত ভাষাগুলির মধ্যে একটি বলুন:",
	"bh": "कृपया निम्नलिखित भाषाओं में से एक बोलें:",
	"bi": "Plis toktok long wan blong ol langwis ia:",
	"bs": "Molimo vas da govorite jednim od sljedećih jezika:",
	"br": "Mar plijit komzhet e-barzh unan eus ar yezhoù-mañ:",
	"bg": "Моля, говорете на един от следните езици:",
	"my": "ကျေးဇူးပြု၍ အောက်ပါဘာသာစကားများထဲမှ တစ်ခုဖြင့် ပြောပါ:",
	"ca": "Si us plau, parleu una de les següents llengües:",
	"ch": "Fañåguen unu na fañåguen i fino' Chamoru:",
	"ce": "Делахьа дӀадолалу хьалхарчу моттешка:",
	"ny": "Chonde mukhulupirireni mtima mmodzi mwa zilankhulo izi:",
	"zh": "请使用以下语言之一交谈：",
	"cv": "Пожалуйста, говорите на одном из следующих языков:",
	"kw": "Mar ples yw genevgh kewsel yn unn a'n yethow ma:",
	"co": "Per piacè parla una di e lingue seguenti:",
	"cr": "ᑮᓂᐋᐧᐁᔨ ᒥᓈᐦᑕᐢᐧᐃᐧᐣ ᓀᐦᐃᔭᐍᐏᐣ ᐅᐢᑯᐦᐊᐧᐤ ᐱᔦᐧᐃᐧᐣ.",
	"hr": "Molimo vas da govorite jednim od sljedećih jezika:",
	"cs": "Prosím mluvte jedním z následujících jazyků:",
	"da": "Venligst tal et af følgende sprog:",
	"dv": "އެއް ބަސް ވާދުކޮށްފި:",
	"nl": "Graag spreken in een van de volgende talen:",
	"en": "Please speak one of the following languages:",
	"eo": "Bonvolu paroli unu el la sekvantaj lingvoj:",
	"et": "Palun rääkige ühel järgmistest keeltest:",
	"ee": "Mía miawo kple ene sia gbe si le afɔwo dometɔ ɖeka:",
	"fo": "Vinsamlegast talað ein av føroysku málinum:",
	"fj": "Vakavinaka mo vosa vaka-Viti:",
	"fi": "Ole hyvä ja puhu yhtä seuraavista kielistä:",
	"fr": "Veuillez parler l'une des langues suivantes :",
	"ff": "Don haaludee ngam nder fulfulde, pulaar, walla pular:",
	"gl": "Por favor, fale unha das seguintes linguas:",
	"ka": "გთხოვთ ისაუბროთ ერთ-ერთ ქვემოთ მოცემულ ენაზე:",
	"de": "Bitte sprechen Sie eine der folgenden Sprachen:",
	"el": "Παρακαλώ μιλήστε σε μία από τις ακόλουθες γλώσσες:",
	"gn": "Eñe'ẽme ñandéve ko tetãme'ẽme:",
	"gu": "કૃપા કરીને નીચે આપેલી ભાષાઓમાંથી એક વિશે વાત કરો:",
	"ht": "Tanpri pale yon nan lang yo ki annapre:",
	"ha": "Don kuɗi game da harshen nan na gaba:",
	"he": "אנא דברו באחת מהשפות הבאות:",
	"hz": "Mweneni nawa otjiherero:",
	"hi": "कृपया निम्नलिखित भाषाओं में से एक बोलें:",
	"ho": "Olgeta tok save long wanpela bilong dispela tokples:",
	"hu": "Kérlek beszéljen az alábbi nyelvek egyikén:",
	"ia": "Parla un del sequente linguas:",
	"id": "Silakan berbicara dalam salah satu bahasa berikut:",
	"ie": "Parla un del sequente linguas:",
	"ga": "Labhair do thoil i dteanga amháin de na teangacha seo a leanas:",
	"ig": "Biko kwuo okwu na asusu ndi a na-esonụ:",
	"ik": "Qaillun pilriani uqautchimun:",
	"io": "Parolez un ek li sequanta lingui:",
	"is": "Vinsamlega talaðu einu af eftirfarandi tungumálunum:",
	"it": "Per favore parla uno dei seguenti linguaggi:",
	"iu": "ᐃᓄᒃᑎᑐᑦ ᖃᐅᔨᒪᓂᖅ:",
	"ja": "次の言語のうちの一つでお話しください:",
	"jv": "Tulung basa Jawi:",
	"kl": "Atorlugit kalallisut oqaluttuarpugut:",
	"kn": "ದಯವಿಟ್ಟು ಕೆಳಗಿನ ಭಾಷೆಗಳಲ್ಲಿ ಒಂದರಲ್ಲಿ ಮಾತನಾಡಿ:",
	"kr": "Don kuɗi game da harshen nan na gaba:",
	"ks": "کٲشُر زَبانہٕ مَنٛز بَاتھ کَرِو:",
	"kk": "Сізге сөйлеу үшін келесі тілдердің біреуін таңдаңыз:",
	"km": "សូមនិយាយជាភាសាមួយក្នុងចំណោមភាសាខាងក្រោមនេះ:",
	"ki": "Tiga atĩa mũno nĩ mũndũ ũmwe wa rĩrĩa ciothe:",
	"rw": "Hitamo umurongo w'umurundi muri rusange rw'ururimi rwose:",
	"ky": "Кыргыз тилинде сүйлөгүлө:",
	"kv": "Ме ӧтны коми кыв вылын:",
	"kg": "Kotanga na kikôngo mosâla mosunú:",
	"ko": "다음 언어 중 하나로 말해 주세요:",
	"ku": "Ji kerema xwe bi yek ji zimanên jêrîn biaxivin:",
	"kj": "OtyiKuanyama otjiKuanyama:",
	"la": "Loquerisne unā ex sequentibus linguis:",
	"lb": "Wann Dir eng vun den nächste Sproochen schwätzt:",
	"lg": "Lambulula mu lulimi lw'omu ku luno:",
	"li": "Kalt mit eine van de volgende sjrieke:",
	"ln": "Kotángá na lokóta mosunú:",
	"lo": "ກະລຸນາເວົ້າໃນພາສາທີ່ມີຢູ່ກ້າວລຸ່ມນີ້:",
	"lt": "Prašome kalbėti viena iš žemiau išvardytų kalbų:",
	"lu": "Kotanga na kiluba mosunú:",
	"lv": "Lūdzu runājiet kādā no zemāk pieejamajām valodām:",
	"gv": "Ta loayrt ayns fer jeh ny çhengaghyn shoh heese:",
	"mk": "Ве молиме зборувајте на еден од следниве јазици:",
	"mg": "Azonao atao hoe amin'ny teny iray amin'ireo manodidina:",
	"ms": "Sila bercakap dalam salah satu daripada bahasa yang disenaraikan:",
	"ml": "താഴെ പറഞ്ഞിരിക്കുന്ന ഭാഷകളില്‍ ഒന്നില്‍ സംഭാഷണം നടത്തുക:",
	"mt": "Jekk jogħġbok tkellem wieħed mill-lingwi li ġejjin:",
	"mi": "Tēnā kōrero i tētahi o ngā reo kei raro nei:",
	"mr": "खालील भाषांपैकी एकात बोला:",
	"mh": "Jipañ ko jebla im barain eake:",
	"mn": "Дараах хэл дээр ярьж үлдээрэй:",
	"na": "Kamimwir otemwen in dorerin Naoero:",
	"nv": "Hózhǫ́ǫgi ádaaníigo Diné bizaad yiilááhgo:",
	"nb": "Vennligst snakk en av følgende språkene:",
	"nd": "Ngiyakusiza ukuthi uye endaweni yezilimi ezilandelayo:",
	"ne": "तपाईँले निम्न भाषाहरू मध्ये एकमा कुरा गर्नुहोस्:",
	"ng": "OtyiKuanyama otjiKuanyama:",
	"nn": "Vennligst talar du eitt av følgjande språka:",
	"no": "Snakk vennligst ett av følgende språkene:",
	"ii": "ꆈꌠ꒿ Nuosuhxop ꉼꅏꋪꃅꄁꂽꂱꇖꊨꏦꏱ:",
	"nr": "Ngiyakusiza ukuthi uye endaweni yezilimi ezilandelayo:",
	"oc": "Parlar d'un dei lengatges seguents:",
	"oj": "ᐊᓂᔑᓈᐯᒧᐎᓐ ᐅᐢᑯᐦᐊᐧᐤ ᐱᔦᐧᐃᐧᐣ.",
	"cu": "Глаголите на един от следните езици:",
	"om": "Afaan Oromootiin haasa'u:",
	"or": "ଓଡ଼ିଆରେ କହିବା ପାଇଁ ଅନୁରୋଧ କରନ୍ତୁ:",
	"os": "ирон æвзагæй дзурын:",
	"pa": "ਪੰਜਾਬੀ ਵਿੱਚ ਗੱਲ ਕਰੋ:",
	"pi": "पाऴिये भाषया एकं वदतु:",
	"fa": "لطفا به یکی از زبان های زیر صحبت کنید:",
	"pl": "Proszę mówić jednym z poniższych języków:",
	"ps": "په یو له لاندې ژبو کې خبرې وکړئ:",
	"pt": "Por favor, fale uma das seguintes línguas:",
	"qu": "Runa Simipi rimananchik:",
	"rm": "Parla in vun da las linguas suandantas:",
	"rn": "Hitamo umurongo w'umurundi muri rusange rw'ururimi rwose:",
	"ro": "Vă rugăm să vorbiți în una dintre următoarele limbi:",
	"ru": "Пожалуйста, говорите на одном из следующих языков:",
	"sa": "संस्कृतम् भाषया एकं वदतु:",
	"sc": "Falat chi unu de is limbas a suta:",
	"sd": "سنڌي، سندھی، سنڌي‎ ۾ ڳالھائيندڙ:",
	"se": "Hupma Davvisámegillii:",
	"sm": "Faalogo i le tasi o gagana nei:",
	"sg": "Kotia yângâ tî sängö:",
	"sr": "Молимо вас да говорите на једном од следећих језика:",
	"gd": "Thoiribh do thoil aig aon de na cànanan seo tha thu fhathast:",
	"sn": "Taura chiShona:",
	"si": "සිංහල භාෂාවෙන් කතා කරන්න.",
	"sk": "Prosím, hovorte jedným z nasledujúcich jazykov:",
	"sl": "Prosim, govorite v enem od naslednjih jezikov:",
	"so": "Soomaaliga ama af Soomaali ku hadla:",
	"st": "Buang ka Sesotho:",
	"es": "Por favor, hable uno de los siguientes idiomas:",
	"su": "Pangapunten dipaké basa Sunda:",
	"sw": "Tafadhali sema katika lugha moja ya hapa chini:",
	"ss": "Sicela uye emalanga lesiSwati:",
	"sv": "Snälla tala på ett av följande språk:",
	"ta": "இந்த மொழிகளில் ஒன்றில் பேசுங்கள்:",
	"te": "ఈ భాషల్లో ఒకదాన్ని మాట్లాడండి:",
	"tg": "Ба якӣ аз забонҳои зерин сухан гуфтан лутф карда бошед:",
	"th": "โปรดพูดภาษาหนึ่งในต่อไปนี้:",
	"ti": "ትግርኛ ተናገር:",
	"bo": "བོད་སྐད་ཤེས་པ་ཅིག་ལ་སློབ་སྦྱོང་རོགས།",
	"tk": "Türkmen dilinde ýada birini gepleşin:",
	"tl": "Mag-usap sa isa sa mga sumusunod na wika:",
	"tn": "Buatshepo ka Setswana:",
	"to": "Lea ki he lea faka-Tonga:",
	"tr": "Lütfen aşağıdaki dillerden birini konuşun:",
	"ts": "Hlanganisa hi Xitsonga:",
	"tt": "Татарча сөйләшегез:",
	"tw": "Twi mu ka:",
	"ty": "Parlez en tahitien:",
	"ug": "ئۇيغۇرچە گەپ قىلىڭ:",
	"uk": "Будь ласка, говоріть однією з наступних мов:",
	"ur": "اردو میں بات کریں:",
	"uz": "O'zbek tilida gapirishingiz mumkin:",
	"ve": "Tshi Venḓa u tevhula:",
	"vi": "Hãy nói bằng một trong những ngôn ngữ sau:",
	"vo": "Volapükäni spiköl:",
	"wa": "Cåzans vosse lingaedje:",
	"cy": "Siaradwch yn un o'r ieithoedd a geir yn isod:",
	"wo": "Parlez en wolof:",
	"fy": "Praat Frysk:",
	"xh": "Khulula ngesiXhosa:",
	"yi": "רעדט אין ייִדיש:",
	"yo": "Ṣe Yorùbá:",
	"za": "Hablais en Zhuang:"
}